# Generated by Django 3.1.3 on 2021-06-24 17:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='Название категории')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='Название тега')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='Название задачи')),
                ('deadline', models.DateField(blank=True, verbose_name='Крайний срок выполнения')),
                ('done', models.BooleanField(default=False, verbose_name='Выполнена')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Изменена')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
        ),
        migrations.CreateModel(
            name='TagTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.tag', verbose_name='Тег')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.task', verbose_name='Задача')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.category', verbose_name='Категория')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.task', verbose_name='Задача')),
            ],
        ),
    ]
