# Generated by Django 3.1.3 on 2021-05-16 23:43

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferalUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('phone_number', models.IntegerField(unique=True, verbose_name='номер телефона')),
                ('code', models.CharField(max_length=6, unique=True, verbose_name='инвайт-код')),
                ('invited_users', models.JSONField(blank=True, null=True, verbose_name='приглашенные пользователи')),
                ('invite_code', models.CharField(blank=True, max_length=6, verbose_name='код пригласившего')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
