# Generated by Django 3.1.3 on 2021-05-14 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referaluser',
            name='code',
            field=models.CharField(default='1Z9aS5', max_length=6, unique=True, verbose_name='инвайт-код'),
        ),
        migrations.AlterField(
            model_name='referaluser',
            name='invited_users',
            field=models.JSONField(blank=True, verbose_name='приглашенные пользователи'),
        ),
    ]
