# Generated by Django 3.1.3 on 2021-05-14 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20210514_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referaluser',
            name='code',
            field=models.CharField(default='0IP2DR', max_length=6, unique=True, verbose_name='инвайт-код'),
        ),
        migrations.AlterField(
            model_name='referaluser',
            name='invited_users',
            field=models.JSONField(blank=True, null=True, verbose_name='приглашенные пользователи'),
        ),
    ]
