# Generated by Django 3.1.3 on 2021-05-14 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20210514_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referaluser',
            name='code',
            field=models.CharField(max_length=6, unique=True, verbose_name='инвайт-код'),
        ),
    ]
