# Generated by Django 3.1.3 on 2021-05-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_auto_20210514_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='referaluser',
            name='invite_code',
            field=models.CharField(blank=True, max_length=6, verbose_name='код пригласившего'),
        ),
    ]
