# Generated by Django 3.1.3 on 2020-12-19 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='Название опроса')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата старта')),
                ('ended_at', models.DateTimeField(blank=True, default=None, verbose_name='Дата окончания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('description', models.CharField(max_length=50, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.SmallIntegerField(choices=[(1, 'Ответ текстом'), (2, 'Ответ с выбором одного варианта'), (3, 'Ответ с выбором нескольких вариантов')], verbose_name='Тип вопроса')),
                ('question', models.CharField(max_length=100, unique=True, verbose_name='Вопрос')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('poll', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.poll', verbose_name='Опрос')),
            ],
        ),
    ]
