# Generated by Django 3.1.3 on 2020-12-20 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='poll',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.poll', verbose_name='Опрос'),
        ),
    ]
