# Generated by Django 3.1.3 on 2020-12-20 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_answer_poll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='poll',
        ),
    ]
