# Generated by Django 3.1.3 on 2020-12-15 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Название опроса')),
                ('number_of_questions', models.SmallIntegerField(verbose_name='Количество вопросов')),
                ('topic', models.CharField(max_length=25, verbose_name='Тема опроса')),
                ('author', models.CharField(blank=True, max_length=25, verbose_name='Автор опроса')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('description', models.CharField(max_length=50, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.SmallIntegerField(choices=[(1, 'Ответ текстом'), (2, 'Ответ с выбором одного варианта'), (3, 'Ответ с выбором нескольких вариантов')], verbose_name='Тип вопроса')),
                ('question', models.CharField(max_length=25, verbose_name='Вопрос')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.poll', verbose_name='Название опроса')),
            ],
        ),
    ]
