# Generated by Django 3.1.3 on 2020-12-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='name',
            field=models.CharField(max_length=25, unique=True, verbose_name='Название опроса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=25, unique=True, verbose_name='Вопрос'),
        ),
    ]
