# Generated by Django 3.1.3 on 2020-12-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20201215_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='author',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='number_of_questions',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='question',
            name='poll',
        ),
        migrations.AddField(
            model_name='poll',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата старта'),
        ),
        migrations.AddField(
            model_name='poll',
            name='ended_at',
            field=models.DateTimeField(blank=True, default=None, verbose_name='Дата окончания'),
        ),
    ]
