# Generated by Django 3.1.3 on 2021-07-19 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_category_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediapost',
            name='number',
            field=models.IntegerField(auto_created=True, verbose_name='Порядковый номер'),
        ),
    ]
