# Generated by Django 3.1.3 on 2021-07-19 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210719_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediapost',
            name='media_link',
        ),
        migrations.AddField(
            model_name='mediapost',
            name='picture',
            field=models.ImageField(blank=True, upload_to='static', verbose_name='Картинка'),
        ),
    ]
