# Generated by Django 3.1.3 on 2021-07-20 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20210719_2137'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='posttocategory',
            unique_together={('post', 'category')},
        ),
    ]
