# Generated by Django 3.1.3 on 2021-05-29 14:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('filmapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 29, 14, 33, 53, 695999, tzinfo=utc), verbose_name='дата создания'),
        ),
    ]
