# Generated by Django 3.1.3 on 2021-05-30 21:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('filmapp', '0002_comment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='star',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmapp.film', unique=True, verbose_name='фильм'),
        ),
        migrations.AlterField(
            model_name='star',
            name='stars',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1, verbose_name='количество звёздочек'),
        ),
    ]
