# Generated by Django 3.1.3 on 2021-05-30 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmapp', '0003_auto_20210531_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='film',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='filmapp.film', verbose_name='фильм'),
        ),
    ]
