# Generated by Django 3.1.3 on 2021-05-30 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmapp', '0004_auto_20210531_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmapp.film', unique=True, verbose_name='фильм'),
        ),
    ]
