# Generated by Django 3.1.3 on 2021-05-30 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filmapp', '0005_auto_20210531_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmapp.film', verbose_name='фильм'),
        ),
        migrations.AlterUniqueTogether(
            name='star',
            unique_together={('user', 'film')},
        ),
    ]
