# Generated by Django 3.1.3 on 2021-04-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=32, verbose_name='Название')),
                ('author', models.TextField(max_length=32, verbose_name='Автор')),
                ('year', models.IntegerField(verbose_name='Год выпуска')),
                ('in_stock', models.BooleanField(default=True, verbose_name='Наличие')),
                ('price', models.IntegerField(verbose_name='Цена')),
            ],
        ),
    ]
